### ISSUE TITLE
Console error is produced when *clrDgHideableColumn hidden property is set to true by default

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1069]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I have an Id column in a data grid that is hidden by default so I set the *clrDgHideableColumn hidden property to true. It should not generate console errors.

### Actual behavior
Errors where generated when hidden property is set to true:
![image](https://user-images.githubusercontent.com/1977391/27179599-e30f513e-5201-11e7-8d5a-bf2b5c574b13.png)

```
<clr-dg-column [clrDgField]="'id'">
        <ng-container *clrDgHideableColumn="{hidden: true}">
            ID
        </ng-container>
    </clr-dg-column>
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
0.9.8
* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@youdz : Could you triage this one?

**Comment by clementcur** [comment]
+1 same symptoms on my side!

**Comment by marcelocarmona** [comment]
I have the same error
https://plnkr.co/nwWWbMmhJyOZNQ02JtAg

**Comment by mathisscott** [comment]
@youdz 
Can you verify that this is fixed in 0.10?

**Comment by youdz** [comment]
The bug is back, my bad. It happens specifically in the case of `*ngFor` on the rows instead of `*clrDgItems`, because in that case cells are rendered before the rest of the datagrid.

Why didn't we have a unit test for this, if we fixed the bug once already?

**Comment by mathisscott** [comment]
@youdz ^

**Comment by gnomeontherun** [comment]
I think this is related to #1500

**Comment by mathisscott** [comment]
Good to know. Thanks!
