### ISSUE TITLE
Strange sizing on the last header column with *ngFor <clr-dg-cell> 

### ISSUE THREAD

**Issue by daniels820** [vmware/clarity#1127]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Table Headers should have the same CSS classes and should have the same style width attribute,
see the last tag of <clr-dg-cell> in DevTools.png

### Actual behavior

Class "datagrid-fixed-width " plus [style.width.%]="header.width" doesnt stick to the last header element of my tableHeaders .
The actual behavior is that the last header column isn't getting the right style attributes, therefore, the columns aren't aligned with the table data.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.3

* **Clarity version:** 0.9.x

* **OS and version:** Chrome
![capturenew](https://user-images.githubusercontent.com/12188713/27688055-d97c708a-5ce1-11e7-97c8-def4aa5bff21.jpg)

![devtools](https://user-images.githubusercontent.com/12188713/27694500-f1ed34c0-5cf4-11e7-85ab-f4586154c9d4.PNG)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
Could you please post a plunker reproducing this? Our various examples correctly align the cells and the columns.

Note that if you are trying to force a fixed width on **every single column** in the datagrid, you will have an issue since it might not add up to the actual width of the datagrid itself. I believe this behavior right now is unspecified, so this might be what you're seeing here.

**Comment by daniels820** [comment]
Hi, @youdz first of all thanks for the quick response.
I've edited the issue and uploaded the right pic that shows I used a dynamic width on every column.... sorry about that...actually this issue #937 is quite like my problem is there a solution for it?

**Comment by youdz** [comment]
As I mentioned, a plunker would be really helpful in investigating this.

Why are you trying to set a percentage width on every column? Do you have a reason for not letting the datagrid size the columns dynamically based on their content?
And the plunker in the issue you linked seems to work fine for me, the bug might have been solved as a side effect.

**Comment by mathisscott** [comment]
We haven't heard back on this. I'm assuming the issue has been resolved.

**Comment by daniels820** [comment]
No, sorry @youdz @mathisscott I've been busy on other matters...
This issue isn't fixed yet, I'm using percentage because I need my table to be responsible....
And it doesn't to be seem fixed in #937 ...
![capture](https://user-images.githubusercontent.com/12188713/28070062-5f8d35f8-6654-11e7-8eca-fb7de5f53c69.PNG)

**Comment by mathisscott** [comment]
@daniels820
I'm not sure that percentage widths on the columns is a good solution for responsive datagrids.

The combination of hiding columns (this can be done with CSS), revealing stacked info in one column, and horizontal scrolling should be a potent combination for responsiveness.

If you can provide us with a plunkr, then I will hop in and try to show you an example using your plunkr.

**Comment by mathisscott** [comment]
@daniels820 
It's been a while. Was my response sufficient to direct you towards building a responsive datagrid?
