### ISSUE TITLE
Signpost's, Dropdown's and Popover's should hide when user taps outside on a mobile device

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#1542]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When user taps (not **clicks**) outside of signpost it should hide. The other types of popover elements, like drop-downs or tooltips, should be have the same behavior.

### Actual behavior
Signpost don't become hidden when the user taps outside of it.

### Reproduction of behavior
Open in browser example of signpost from official documentation page on any mobile device:
https://vmware.github.io/clarity/documentation/signposts

### Environment details
* **Angular version:** 4.4.4

* **Clarity version:** 0.10.7

* **OS and version:** iOS 10.2.1

* **Browser:** Mobile Chrome 55.0.2883.79 | iOS 10.2.1 Safari

**Comment by adityarb88** [comment]
@hippee-lee: Could you please take a look at this?

**Comment by belyan** [comment]
I guess that if add the support of event **touchstart** in signpost trigger directive, then this should solve the problem. I found this solution here:
https://stackoverflow.com/questions/7892863/jquery-click-not-working-with-ipad

**Comment by hippee-lee** [comment]
Hi @belyan - I'm looking at this issue now. Adding touch start seems to cause some issues opening a signpost and did not seem to fix the close issue.

**Comment by hippee-lee** [comment]
Investigation revealed what this is related to how iOS (I haven't confirmed Mobile Chrome yet) handles click events. Unless the tap takes place on an input or a link/button the click event doesn't bubble up. 

In the short debug session I was able to `fix` it by adding ```cursor: pointer;``` to the body (or any of the layout container element stylesheets. Given the way we handle popovers now this doesn't seem like a quick one line fix. 

Here are some resources form further research:

1. https://www.quirksmode.org/blog/archives/2010/09/click_event_del.html
2. http://gravitydept.com/blog/js-click-event-bubbling-on-ios

I'm marking this as a bug and moving it into the backlog.

**Comment by gnomeontherun** [comment]
This has been fixed by #2923 and I'm going to close this as resolved.
