### ISSUE TITLE
[UI] Dark theme select options are not visible

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1853]
### Edit
Stackblitz with v2 reproduction: https://stackblitz.com/edit/gh-1853-select-input-dark-theme-issue

**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Select option text should be readable

### Actual behavior
Select option text is not visible

### Reproduction of behavior
![edge_select-bug](https://user-images.githubusercontent.com/433692/34784940-8976ce86-f5e4-11e7-82cb-5a59fdc501f7.png)
![firefox-select-bug](https://user-images.githubusercontent.com/433692/34784941-899ce878-f5e4-11e7-9128-03a3b44c4b80.png)
![ie_11_select-bug](https://user-images.githubusercontent.com/433692/34784942-89ba24a6-f5e4-11e7-8a6f-57b1b0689af6.png)

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:**

* **OS and version:** Windows 10

* **Browser:** [ Chrome XX, IE11, Firefox ]

**Comment by RoelRoel** [comment]
This is still not fixed correctly. Now the text of the options has a white color but the options have no background color so you can't read the text.

**Comment by hippee-lee** [comment]
This was fixed but it looks like a regression was introduced since then.

Stackblitz with a reproduction: https://stackblitz.com/edit/gh-1853-select-input-dark-theme-issue

**Comment by hippee-lee** [comment]
This was fixed via #3941

**Comment by rogerfar** [comment]
@hippee-lee this is either broken again, or wasn't fixed yet:
https://stackblitz.com/edit/clarity-dark-theme-v2-enzagq?file=src/app/app.component.html

![image](https://user-images.githubusercontent.com/1142915/72763163-ac9c8880-3b9f-11ea-93f0-0f31c8e88787.png)

**Comment by hippee-lee** [comment]
- Chrome / Safari work as expected
- Firefox does not work. 
- Still need to check IE11 / Edge

**Comment by rogerfar** [comment]
Wait, how does Chrome work as expected? My screenshot is from Chrome 79.

**Comment by hippee-lee** [comment]
I updated to the latest versions. 
https://stackblitz.com/edit/clarity-dark-theme-v2-dnad9x

**Comment by ezekeal** [comment]
Confirmed sill an issue
clarity-v2-dark
FF 77.0.1
OSX: 10.15.4 - dark

**Comment by gnomeontherun** [comment]
I don't see this behavior while reviewing this issue. If it persists, please provide an updated demo and details with current versions of Clarity for us to triage. Closing as stale and appearing to be fixed.

**Comment by rogerfar** [comment]
@gnomeontherun it's OK looking I suppose, if this is by spec then yeah, let's leave it. But I still have to add extra hack CSS to make to colors work. At least it's consistent on every browser.

https://stackblitz.com/edit/clarity-v4-dark-theme-abnpwk?file=src%2Fapp%2Fapp.component.html

![image](https://user-images.githubusercontent.com/1142915/106470336-96393600-645d-11eb-9bb7-c3a5bc87cf76.png)

**Comment by gnomeontherun** [comment]
@hippee-lee can you take a look at this this week?

**Comment by hippee-lee** [comment]
@rogerfar - can you explain more about what needs a css override? I'm not seeing any css to override the default styles in [this](https://stackblitz.com/edit/clarity-v4-dark-theme-abnpwk?file=src%2Fapp%2Fapp.component.html) example from above. 

The issue here is specific to the options in a native select element - originally there was an issue with the font color not being set in dark theme and then there were some regressions that broke that. 

I don't see anything broken in the stackblitz or any custom css that applies to the font color in the select menu.

**Comment by rogerfar** [comment]
That's correct, the original issue was the font color being wrong in the selects, black on black.

But that's why I said, it's OK working, some of the other selects are now completely missing styling.

**Comment by hippee-lee** [comment]
Ok, which ones? Sorry I don't see any issues in the stackblitz or the screen captures. What am I missing?

**Comment by rogerfar** [comment]
I'm referring to the first 3 selects in the stackblitz:

![image](https://user-images.githubusercontent.com/1142915/106513259-f5b03980-648f-11eb-9905-1ff411f22cdf.png)

**Comment by hippee-lee** [comment]
They look like they are working to me:

## Edge
![edge](https://user-images.githubusercontent.com/433692/106514684-6e5fc780-6489-11eb-8d2c-a30d22a02b92.png)

## Firefox
![firefox](https://user-images.githubusercontent.com/433692/106514718-77e92f80-6489-11eb-83b9-5da00799ade5.png)

## Safari
![safari](https://user-images.githubusercontent.com/433692/106514739-80416a80-6489-11eb-8a88-8c297682cd52.png)

## Chrome
![chrome](https://user-images.githubusercontent.com/433692/106514761-88010f00-6489-11eb-935a-a425d79306e1.png)

What am I missing?

**Comment by RoelRoel** [comment]
They are not dark themed.

**Comment by rogerfar** [comment]
@hippee-lee I was hoping for something like this, like it was in v3:

![image](https://user-images.githubusercontent.com/1142915/106522000-4a59b180-649c-11eb-87a7-a6ef340fe49e.png)

**Comment by hippee-lee** [comment]
Ah ok I see. Sorry I should have clarified first. There are only a couple of properties that can be applied to the select options element. It is OS dependent and iir background color isn't one of them. I believe we only have control over the text color.

**Comment by hippee-lee** [comment]
Clarity doesn't set any style for the background color **of the options** ... that comes from the OS. When I switch my macOS appearance to Dark, this is what a demo with Clarity v3 looks like:

### Dark
![Screen Shot 2021-02-01 at 3 52 26 PM](https://user-images.githubusercontent.com/433692/106532811-c1e00e80-64a5-11eb-8940-a1e091893f06.png)

### Light
![Screen Shot 2021-02-01 at 3 55 58 PM](https://user-images.githubusercontent.com/433692/106532927-04a1e680-64a6-11eb-9216-c89bc61b636a.png)

I didn't go through all of the browsers but expect they will behave similar.

**Comment by rogerfar** [comment]
Odd that it does work on the multi selects, it's the same thing but with an added attribute as a regular select.

**Comment by hippee-lee** [comment]
The options dropdown _thing_ (not a technical term) is owned by the OS, not the browser. Some browsers do allow css to set style, others do not. Since it is owned by the OS we let it be. 

I'm going to close this as its not something we have control over. Please lmk if you have a reason to keep it open.

**Comment by rogerfar** [comment]
I don't think that's entirely true, why design all other elements to have dark backgrounds, but the select?

This code works fine for all browsers in Windows:
https://stackblitz.com/edit/clarity-v4-dark-theme-dhwreq?file=src%2Fstyles.css
Chrome:
![image](https://user-images.githubusercontent.com/1142915/106545779-38413880-64c7-11eb-8025-21c5fa6a242a.png)
Firefox:
![image](https://user-images.githubusercontent.com/1142915/106545809-468f5480-64c7-11eb-8a22-e32751d19132.png)

**Comment by hippee-lee** [comment]
That code will not work at all in Safari or chrome on macOS.

**Comment by RoelRoel** [comment]
Does that matter?

**Comment by hippee-lee** [comment]
This is a really old issue. In the last discussion about select option backgrounds that I remember, we didn't want to implement styles that were not consistent across all browsers/OSes. 

That said, I looked back at v2, v3 and v4 on macOS: Safari, Chrome and Firefox and Windows: Edge, Firefox and Chrome and it doesn't look like we have ever implemented a background-color for select options in any of those versions. We do however have it implemented in the new Core select components. 

Since this issue was about option text not being visible I'd like to leave it closed because option text is currently visible in light / dark themes for `@clr/ui` on all supported OSes and browser combos. 

If the request is to have the background color for select options be specific to the themes for the browsers that support it, please open up a new issue and request it there so we can keep this issue separate from  the enhancement request.
