### ISSUE TITLE
Datepicker breaks modal layout

### ISSUE THREAD

**Issue by jansivans** [vmware/clarity#2092]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

Initial state of modal:
![](https://i.imgur.com/N338lc6.png)
After datepicker icon was clicked:
![](https://i.imgur.com/IlV8jhe.png)

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.9

* **OS and version:** Windows 10

* **Browser:** all

**Comment by adityarb88** [comment]
@jansivans: The issue here is with the current forms. Since the `.form-group` has `position: relative` on it, it interferes with the positioning all popovers under it. @gnomeontherun is currently are working on a new version of forms. You can follow the progress here: https://github.com/vmware/clarity/issues/932

We will test this use case as part of the implementation.

**Comment by tflanitzer** [comment]
Is there no workaround for this? Because this issue basically means the datepicker cannot be used in modals at the moment.

**Comment by speti43** [comment]
Do you have any estimation, when this bug will be fixed?
We can't go with any workaround, we have to use pure clarity solution.

Thanks!

**Comment by mathisscott** [comment]
@gnomeontherun 
Was this fixed with the new grid? Any advice or a stackblitz to give us an idea of the changes required to address this with the new grid?

**Comment by gnomeontherun** [comment]
The new grid should fix this, even if you are using the old forms. Closing as resolved.

**Comment by SGauts** [comment]
I am still facing the same issue. 
Did anyone find a solution?
I am using the latest clarity and angular versions.

**Comment by gnomeontherun** [comment]
@SGauts This is pretty old and I'm not sure exactly what you are doing. There are a few cases where the date picker gets clipped due to position relative, which should be fixed soon with our updated popovers. However, if you are using a date picker in a place with relative positions around it, this may still happen (like in a modal) and for now you have to manually position the date picker so it has space. Otherwise, create a demo of your specific case and open a new ticket.
