### ISSUE TITLE
Using clDgRowSelection affects cell width in Datagrid

### ISSUE THREAD

**Issue by bniedermeyer** [vmware/clarity#2525]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Using `clDgRowSelection` should not impact table formatting. 

### Actual behavior

When adding `[clDgRowSelection]="true"` to a `clr-datagrid` component the width of cells are changed and the table content is no longer contained in the width of the grid. 

### Reproduction of behavior

The stackblitz templates are not loading for me - I've uploaded a working repro [here](https://github.com/bniedermeyer/clarity-selectable-row)

### Environment details

* **Angular version:** 6.1.0

* **Clarity version:** 0.12.7

* **OS and version:** Windows 10

* **Browser:** [Chrome 68 | Firefox 61 | Edge 40]

**Comment by hippee-lee** [comment]
@bniedermeyer - I ported the code in the github repo to a stackblitz. Can you confirm that this is the same as in the repo and that overflow is an issue `clDgRowSelection`? I'm not seeing the cells overflow. on StackBlitz. 

https://stackblitz.com/edit/clarity-datagrid-issue-2525-reproduction

**Comment by bniedermeyer** [comment]
Interesting. I'm not seeing the issue in Stackblitz either and the code is the same as my repro. I wonder if project setup has something to do with it? Originally I saw this issue in my app, then created the repro project to make sure it wasn't something with my original application causing the issue. 

For the repro I followed these steps:
1. `ng new clarity-selectable-row`
2. `ng add @clr/angular`
3. `npm install bootstrap@4.0.0-alpha.5` to deal with missing peer dependency warning
4. Added code to app.component.html and app.component.ts to recreate the issue.

Perhaps there is a difference in the way the Stackblitz apps are setup vs how they're setup when using the `ng add` command? I'm not at a place where I can test a project where I've manually added Clarity. I will do that asap and report back.

**Comment by hippee-lee** [comment]
It looks like the stackblitz was not using hte latest version of Clarity. I updated it and it reproduced the issue. Thanks for reporting this. 

We will take a look into it and see whats causing it. 
https://stackblitz.com/edit/clarity-datagrid-issue-2525-reproduction

**Comment by zerocewl** [comment]
Same here, if i use clDgRowSelection with v 0.12.7 the table does not resize the content of the rows according to the column size.

Workaround: use v 0.12.6 or remove clDgRowSelection.

**Comment by youdz** [comment]
Should be fixed by #2508. It broke when we made the `clDgRowSelection` feature more accessible.

This feature keeps creating issues for us, we highly recommend not using it since we believe it's both bad for accessibility  reasons and doesn't bring anything in terms of UX (or worsen UX in some cases). Until #2508 goes in, we don't have time to allocate to fix this yet another time.

**Comment by alonbez** [comment]
Looks like #2508 was merged but the issue still reproducing.

**Comment by gnomeontherun** [comment]
These changes are not yet in master, they were in a feature branch that hasn't been released.

**Comment by youdz** [comment]
Fixed by #2670.
