### ISSUE TITLE
[Website blocked in Russia] Pls change clarity.design website IP address

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3063]
## Describe the bug

Since the end of the last year, I was sometimes experiencing outage of clarity.design website.
Using ping over clarity.design address, I found requests goes to 167.99.137.12.
Then I found that this IP address was blocked in Russia by court due to some extremist content was accessible on this IP address. I don't think it can possibly be related to Clarity website. I guess this IP could be used by another website. If this is hosted on GH pages, then it could be 1 particular repo on GH, which is not related to Clarity.

Anyway, it would be nice if you could switch website to another IP address if this is possible.

Checked this info here (in Russian): http://blocklist.rkn.gov.ru/

**Comment by gnomeontherun** [comment]
@sdurnov We've deployed the website again and it might be on a different IP range, does it show for you now? Just curious if this is a consistent or intermittent issue.

**Comment by sdurnov** [comment]
@gnomeontherun sadly, this is still an issue for me. Just tried - doesn't load. I've cleared DNS cache, but pinging clarity.design shows same old IP address.

**Comment by sdurnov** [comment]
@gnomeontherun looks like I had to wait few minutes before DNS cache was actually cleared. Now it works. Closing for now.

**Comment by sdurnov** [comment]
![image](https://user-images.githubusercontent.com/32732457/52133077-b2792100-2651-11e9-8505-79c307c3f887.png)
