### ISSUE TITLE
clr-datagrid not redrawing table on update - items are appended

### ISSUE THREAD

**Issue by rmjoia** [vmware/clarity#4257]
## Description of the problem
_I'm using a clr-datagrid with angular 9.rc-10 (upgranding) and using ngrx, I noticed that when we cancel the changes made to the data in the row, the new state is appended to the datagrid instead of replacing it. My code worked just fine on angular 8 (before the upgrade).
If I change the properties manually one by one it updates, but once I change the whole object, it's appended._ 

## How to reproduce

[_Example_](https://stackblitz.com/edit/angular-md7hfw)

1.  Change one or more of the elements on the datagrid
2.  Click cancel

## Expected behavior

_The original value(s) should be retrieved reseting the state._

## Versions

**App**

* Angular: [9 rc *]
* Node: [13]
* Clarity: [2.3.6]

**Device:**

* Type: [Dell Precision 5530]
* OS: [Windows 10]
* Browser [chrome]
* Version [79.0.3945.130]

**Comment by gnomeontherun** [comment]
This is an issue with the changes in Ivy, which are fixed in the open PR for #4232

**Comment by harmoniemand** [comment]
still happening with 
    "@angular/core": "~9.0.1",
    "@clr/ui": "^3.0.0-next.8",

is it already integrated?

**Comment by gnomeontherun** [comment]
Did you also update @clr/angular? I updated your demo and don't see an issue. 

https://stackblitz.com/edit/angular-mctp7y?file=package.json

Closing as resolved, please reopen if you can identify or reproduce the issue again.

**Comment by rmjoia** [comment]
thanks for the support @gnomeontherun!
