### ISSUE TITLE
SCRIPT1014: Invalid character when running on IE 11

### ISSUE THREAD

**Issue by davidrourke** [vmware/clarity#4327]
## Describe the bug

Upgraded to Angular v9 and Project Clarity v3 and when running application on IE 11, I am receiving the following error:

SCRIPT1014: Invalid character
vendor.js (123110,64)

When I navigate to the code causing the issue, I am taken to this line:

const styles = lit_element__WEBPACK_IMPORTED_MODULE_0__["css"] `.clr-sr-only{position:absolute;clip:rect(1px, 1px, 1px, 1px);clip-path:inset(50%);padding:0;border:0;height:1px;width:1px;overflow:hidden;white-space:nowrap;top:0;left:0}*,*:before,*:after,:host{box-sizing:border-box}:host{font-family:inherit;contain:content}slot{font-family:inherit}
`;

I believe the problem is because "`" (template strings) is not supported by IE. 

## How to reproduce

Since Stackblitz is currently having issue with IE 11, I cannot provide an example app.

## Expected behavior

I should be able to run an application in IE 11 without getting this error.

## Versions

**App**

* Angular: 9.0.4
* Node: 12.9.0
* Clarity: 3.0.0

**Device:**

* Type: MacBook Pro
* OS: Windows 10 (VirtualBox)
* Browser: IE 11
* Version: 11.657.18362.0

## Additional notes

Same application runs just fine in Angular 8, Project Clarity 2.3.8

**Comment by gnomeontherun** [comment]
Hi @davidrourke can you provide a reproduction to review? My dev app doesn't show this issue, so I'd like to know what the configuration of your project is to see how its compiling.

**Comment by davidrourke** [comment]
@gnomeontherun I am building the application targeting 'es5', so I have a specific configuration like so:

"es5" : {
    "tsConfig": "./tsconfig-es5.app.json"
}

And the contents of the tsconfig-es5-app.json are:

{
    "extends": "./tsconfig.app.json",
    "compilerOptions": {
         "target": "es5"
    }
}

And I kick it off with the following script action in the package.json file:

"es5": "ng serve --configuration es5"

I used this same configuration to build the application on Angular 8 and Project Clarity 2.x which ran without producing the error.

**Comment by gnomeontherun** [comment]
My application also targets `es5` so there is more to this. Can you provide a reproduction?

**Comment by davidrourke** [comment]
@gnomeontherun I have created an application that reproduces the issue and have attached.
[angular9.zip](https://github.com/vmware/clarity/files/4277572/angular9.zip)

**Comment by LotD86** [comment]
I got the same issue in an angular 8 project, even Microsoft Edge woun't load the app.
Using the "tsconfig-es5.app.json" workaround does not help.

**Comment by gnomeontherun** [comment]
@davidrourke Sorry for the delays here, as you can imagine its a bit of a hectic time.

I tried your reproduction and don't see the error message, but IE11 simply doesn't load anything when I run it normally. I tried with the es5 configuration, and see the error message. 

The site appears correctly with my version of Edge, without an error. 

This appears to be an issue specifically with Core. Our next release should decouple the need to include Core by default, and that should actually fix your problem I believe.

@LotD86 Is this the same issue? Are you using Clarity 3 or 2?

**Comment by coryrylan** [comment]
I downloaded the example and it does work in IE11 and even pre-chromium Edge, however with some restrictions. Since Angular 8 the Angular CLI defaults to ES2015 in dev watch mode and only partially supports ES5 in dev watch mode. https://angular.io/guide/deployment#differential-loading

Following the docs to renable ES5 support in dev mode only solves part of the problem as the CLI **wont compile any transitive dependencies that are not ES5**. For Clarity specifically this issue _might_ be improved in the next release or the following. We are still investigating ways to help make this easier for existing apps, but long term as more packages shift to shipping ES2015+ modules this will become more prevalent.

To get the demo running run `ng build prod` then run a local web server on the final prod build output `cd dist/angular9 && lite-server`. The app will run in IE now. 

IE11
<img width="1443" alt="Screen Shot 2020-03-31 at 8 30 38 PM" src="https://user-images.githubusercontent.com/2021067/78090431-b4428f80-738f-11ea-8080-a97e43b1ff76.png">

Pre-Chromium Edge 18. Latest Edge is now version 80 with Chromium
<img width="1314" alt="Screen Shot 2020-03-31 at 9 08 26 PM" src="https://user-images.githubusercontent.com/2021067/78091916-da6a2e80-7393-11ea-81e0-87cd061a082e.png">

**Comment by gnomeontherun** [comment]
The next release of Clarity should resolve the immediate issue. So long as you run the project with prod mode, so Angular CLI compiles your dependencies, will also be a way to get around the issue.

**Comment by krawinkelm** [comment]
1) What does "run the project with prod mode" _really_ mean? Just running a prod build does not resolve the problem.
2) In which release of Clarity it's planned to fix the bug? The bug is still there in 3.1.0.

**Comment by coryrylan** [comment]
Closing as this is working as expected behavior with the [Angular CLI ie11 support](https://angular.io/guide/deployment#differential-loading).
