### ISSUE TITLE
clr-datepicker-view-manager opens behind modal backdrop

### ISSUE THREAD

**Issue by zierler-f** [vmware/clarity#4825]
## Describe the bug

When opening the date picker inside a modal, the clr-datepicker-view-manager opens behind the modal backdrop and therefore is not clickable.

## How to reproduce

[https://stackblitz.com/edit/clarity-v3-light-theme-saauxu](https://stackblitz.com/edit/clarity-v3-light-theme-saauxu)

1.  Open Stackblitz link
2.  Click on calendar symbol
3.  See error as date picker opens behind modal backdrop

## Expected behavior

The date picker opens in front of modal backdrop and is clickable.

## Versions

**App**

- Angular: 9.1.12
- Node: 12.18.3
- Clarity: 3.1.5

**Device:**

- Type: Windows
- OS: Windows 10
- Browser: Firefox Developer
- Version: 79.0b9

## Additional notes

A possible short term fix is adding the following code in your styles.css in the project root:
```
.datepicker {
  z-index: 1100 !important;
}
```

**Comment by gnomeontherun** [comment]
This has been resolved in the latest v3 release, should have been fixed by #4703. When I update your stackblitz demo to latest Clarity v3, the date picker appears above the modal.

**Comment by zierler-f** [comment]
I upgraded all @clr packages to 3.1.5 here: [https://stackblitz.com/edit/clarity-v3-light-theme-9nrk8e](https://stackblitz.com/edit/clarity-v3-light-theme-9nrk8e)

Unfortunately the problem persists.

**Comment by bdryanovski** [comment]
This is resolve into the latest release `3.1.6`
