### ISSUE TITLE
Clarity Icons breaks when added via webpack to aspnetcore-spa

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#947]
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I expect clarity-ui, icons, and angular to load and run correctly in the new aspaspnetcore-spa project
- https://github.com/aspnet/JavaScriptServices/tree/dev/templates/AngularSpa

### Actual behavior
Clarity-Icons throws errors and crashes the app.

![webpack errors](https://cloud.githubusercontent.com/assets/7592811/26265359/d73823b2-3cae-11e7-904d-7409d0a39fcc.png)
![clr_icons_err_chrome1](https://cloud.githubusercontent.com/assets/7592811/26265363/dc178922-3cae-11e7-9d3b-02a0fae13bca.png)
![clr_icons_err_chrome2](https://cloud.githubusercontent.com/assets/7592811/26265368/de1799c4-3cae-11e7-82ce-ab373926429a.png)
![clr_icons_err_edge1](https://cloud.githubusercontent.com/assets/7592811/26265370/e057ab70-3cae-11e7-9fc8-6d72584d1b4a.png)
![clr_icons_err_edge2](https://cloud.githubusercontent.com/assets/7592811/26265373/e226ebfa-3cae-11e7-8a9b-327eac9ed71e.png)


### Reproduction of behavior
https://github.com/jacobbutton/clr_icons_aspnetcore-spa_webpack

comment out all references to clarity-icons
...webpack.config.vendor.js - line 34 and 38
...Client/app/components/fetchdata/fetchdata.component.ts - line 3
run webpack on webpack.config.vendor.js and the project will run without error.




### Environment details
Angular 4.1.2
Clarity 0.9.5
Win10
Visual Studio 2017

* **Browser:** Chrome, Edge (only ones tested)

**Comment by mathisscott** [comment]
@shijir - do you think this is related to #940 ?

**Comment by Shijir** [comment]
@mathisscott I believe so as it's using webpack.

**Comment by Shijir** [comment]
@jacobbutton we've just released a patch version, `0.9.5-patch` so please install that.
https://www.npmjs.com/package/clarity-icons. And let us know if it fixes your problem.

**Comment by jacobbutton** [comment]
I really appreciate the quick response, but unfortunately, it has not resolved the issue. After installing the patch I was left with this error.

```
PS C:\Users\jacob\Documents\Projects\AngularSeed\Source> webpack --config webpack.config.vendor.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'loader-runner'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jacob\Documents\Projects\AngularSeed\Source\node_modules\webpack\lib\NormalModule.js:25:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Installing loader-runner webpack was able to execute, but I'm still left with this error after running the application.

```
vendor.js:79819 Uncaught SyntaxError: Unexpected token &&

main-client.js:714 Uncaught ReferenceError: vendor_e5fbe547ed8701dc9d50 is not defined    
at Object.<anonymous> (main-client.js:714)    
at __webpack_require__ (main-client.js:658)    
at fn (main-client.js:86)    
at Object.module.exports (main-client.js:1421)    
at __webpack_require__ (main-client.js:658)    
at fn (main-client.js:86)    
at Object.<anonymous> (main-client.js:4102)    
at __webpack_require__ (main-client.js:658)    
at module.exports (main-client.js:707)    
at main-client.js:710
```

**Comment by mathisscott** [comment]
Thanks for getting back to us @jacobbutton. We will add this to our backlog and try to take a look at this.

**Comment by Shijir** [comment]
Wait, looking at these screenshots, I am now wondering if you have custom elements polyfill installed? @jacobbutton 
![](https://cloud.githubusercontent.com/assets/7592811/26265370/e057ab70-3cae-11e7-9fc8-6d72584d1b4a.png)

![](https://cloud.githubusercontent.com/assets/7592811/26265373/e226ebfa-3cae-11e7-8a9b-327eac9ed71e.png)

**Comment by jacobbutton** [comment]
It is. Or, at least it should be.

package.json
https://github.com/jacobbutton/clr_icons_aspnetcore-spa_webpack/blob/master/package.json

vendor config
https://github.com/jacobbutton/clr_icons_aspnetcore-spa_webpack/blob/master/webpack.config.vendor.js

**Comment by Shijir** [comment]
Does it happen in only production mode? Or does it also happen during development? 
In your package.json you have these:
```
    "clarity-angular": "^0.9.5",
    "clarity-icons": "^0.9.5",
    "clarity-ui": "^0.9.5",
```
I am not sure having carot would enable you download `v0.9.5-patch`. So please make sure you have installed `v0.9.5-patch` versions. Also, try changing this
```
'clarity-icons/clarity-icons.min.js',
'clarity-angular'
```
to
```
'clarity-icons',
'clarity-angular'
```

**Comment by jacobbutton** [comment]
Sorry, I do have the patch installed on my local copy. I haven't committed those changes to the demo app I put up on github.

Your suggestion has resolved the error I was getting in chrome. Edge is still showing the 'customeElements' is undefined error as before.

**Comment by jacobbutton** [comment]
It's happening in development

**Comment by Shijir** [comment]
>Your suggestion has resolved the error I was getting in chrome. Edge is still showing the 'customElements' is undefined error as before.
Edge needs the customElements polyfill. Chrome supports customElements by default. So what you are describing tells me the customElements polyfill hasn't been installed properly.

**Comment by mathisscott** [comment]
@jacobbutton 
Did @Shijir's suggestion work for you? We haven't heard back...

**Comment by jacobbutton** [comment]
I think he might be correct that customElements isn't loading correctly, but I can't figure out why. customElements is in my node-modules folder, and it's in my vendor webpack which compiles without error. I've even tried referencing the polyfills and clarity-icon files directly in my Index.cshtml file. No luck. Still looking into it.

If you have anymore suggestions, please let me know. Otherwise, I'll post back if I figure it out.

**Comment by jacobbutton** [comment]
I'm still working on this when I have free time, but actual project development taken taken priority at the moment.

I was able to track this down and it might shed more light on the situation.

https://github.com/webcomponents/custom-elements/issues/90

Now I'm not too proud to admit, a lot of this is over my head. My background is in C# ASP.NET Web Forms and I'm just now making my foray into single page applications, angular, and this horrid thing known as webpack.

It seems CustomElements doesn't play nicely with the project seed I'm using due to ES6 to ES5 transpiling (I have a vague understanding of what that is) and I'm sure if I knew more about configuring webpack I could figure out a way to make all this work, but it seems overly complex for something that should 'just work' out of the box.

https://github.com/aspnet/JavaScriptServices

Now I understand CustomElements not working with this seed isn't your responsibility but the seed project I'm using is the official Microsoft ASP.Net Core project build for angular. Most online tutorials (the ones I've been following along with on udemy) for working with .Net Core and angular recommend this seed to start with. A significant number of developers will be starting new projects with this seed. It's my opinion that clarity does seem to be one of the better frameworks available, but if it doesn't work out of the box it's a huge hindrance to people like me who are just getting started with the framework.

**Comment by mathisscott** [comment]
@jacobbutton 
This definitely appears to be a webpack + aspnetcore-spa + web components issue. I would recommend trying to follow some of the guidance in that issue you referenced.

At this time, Clarity Icons asks users to load in the web-components shim before Clarity Icons. Perhaps in your specific situation, it may be better to try loading https://github.com/skatejs/web-components

**Comment by yelhouti** [comment]
I have exactly the same bug and I don't use asp: `Unexpected token &&`
this happens when I `import "../../node_modules/clarity-icons/clarity-icons.min.js";`
any news?

**Comment by Shijir** [comment]
@yelhouti you shouldn't try to import `clarity-icon.min.js` because it's not an importable module. It should be just a non-relative import like this:

```
import  "clarity-icons";
```

**Comment by yelhouti** [comment]
Indeed my bad thank you very much, but now some shapes are missing, I tried 
```
import {ClarityIcons} from "clarity-icons";
import { AllShapes } from "clarity-icons/src/shapes/all-shapes";
ClarityIcons.add(AllShapes);
```
but module want compile: Module build failed: Error: ENOENT: no such file or directory, open '.... node_modules/clarity-icons/src/shapes/all-shapes.js'

**Comment by mathisscott** [comment]
Thanks for the feedback, @yelhouti . We're currently working on improving our documentation for clarity icons!

**Comment by k-vekos** [comment]
@yelhouti could you please share the working `webpack.config.vendor.js` and `app.module.ts`? I have the same issue and it's hard to tell what configuration finally worked for you. Thanks!
